language: python
python: 3.5
sudo: true
services:
  - docker

addons:
  apt:
    packages:
    - npm

before_install:
  - docker pull enhancedsociety/solsa
  - npm install -g solhydra 

install:
  - git clone --recurse-submodules -q -b enhanced_mods https://github.com/enhancedsociety/ico.git

script:
  - mkdir solhydra-out
  - cd ico
  - for contract in $(ls contracts/**/*.sol); do echo $contract; docker run -it --rm -v $(pwd):/src:ro enhancedsociety/solsa -a $contract; echo; done
  - solhydra --contract-dir=./contracts --dep-dir . --dest-dir=../solhydra-out/


deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: solhydra-out
  on:
    branch: master
  verbose: true