language: python
python: 3.5
sudo: true
services:
  - docker

addons:
  apt:
    packages:
    - npm

before_install:
  - docker pull enhancedsociety/solsa
  - npm install -g solhydra 
  - docker pull rmi7/solhydra_solidity-coverage:1.0
  - docker pull rmi7/solhydra_oyente:1.0
  - docker pull rmi7/solhydra_solidity-analyzer:1.0
  - docker pull rmi7/solhydra_mythril:1.0
  - docker pull rmi7/solhydra_solhint:1.0
  - docker pull rmi7/solhydra_solgraph:1.0
  - docker pull rmi7/solhydra_solium:1.0

install:
  - git clone --recurse-submodules -q -b enhanced_mods https://github.com/enhancedsociety/ico.git

script:
  - mkdir solhydra-out
  - cd ico
  - for contract in $(ls contracts/**/*.sol); do echo $contract; docker run -it --rm -v $(pwd):/src:ro enhancedsociety/solsa -a $contract; echo; done
  - travis_wait solhydra --contract-dir=./contracts --dep-dir . --dest-dir=../solhydra-out/


deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: solhydra-out
  on:
    branch: master
  verbose: true