language: python
python: 3.5

sudo: true

services:
  - docker

cache:
    directories:
     - /home/travis/.cargo/

before_install:
  - curl https://sh.rustup.rs -sSf | sh -s -- -y
  - export PATH="$HOME"/.cargo/bin:$PATH
  - cargo install solsa --force
  - docker pull enhancedsociety/solc
  - docker pull enhancedsociety/solium
  - docker pull enhancedsociety/oyente
  - docker pull enhancedsociety/mythril

install:
  - git clone --recurse-submodules -q -b enhanced_mods https://github.com/enhancedsociety/ico.git
  - pip install -r requirements.txt

script:
  - mkdir solsa-out
  - cp .soliumrc.json .soliumignore ico/
  - ./run_report.py -o solsa-out ico/crowdsales/*.yml


deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: solsa-out
  on:
    branch: master
  verbose: true