language: python
python: 3.5
sudo: true
services:
  - docker

addons:
  apt:
    packages:
    - cargo

before_install:
  - cargo install solsa
  - docker pull enhancedsociety/solc
  - docker pull enhancedsociety/solium
  - docker pull enhancedsociety/oyente
  - docker pull enhancedsociety/mythril

install:
  - git clone --recurse-submodules -q -b enhanced_mods https://github.com/enhancedsociety/ico.git

script:
  - mkdir solsa-out
  - cd ico
  - for contract in $(ls **/*.sol); do echo $contract; solsa -o ../solsa-out/$(basename -- $contract).html -f $contract; echo; done
  - cd ../solsa-out
  - ../make_index.sh > index.html


deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: solsa-out
  on:
    branch: master
  verbose: true